apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kqrf95rcy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kqrf95rcy-go 
  name: kqrf95rcy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kqrf95rcy-go 
