apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kqrf95rcy-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:c687912d286794b27eec42b86c6f7d1b1b044a99@sha256:f8c9bfa7a195b6d385eface32aa6bbc84feef1e201df1c4c6314ac9379680075
          name: container-image
